### ISSUE TITLE
Usage of type 'unicode' in Python 3.x is not defined

### ISSUE THREAD

**Issue by martindufort** [berlincode/ndb-orm#1]
I'm adding a KeyProperty to a model object and I'm getting an error about unicode type being not defined. 

`  
File "/usr/local/lib/python3.6/site-packages/ndb_orm/model.py", line 1961, in __init__
    if isinstance(kind, unicode):
NameError: name 'unicode' is not defined
`

**Comment by berlincode** [comment]
This error should be fixed by version 0.8.1.
