### ISSUE TITLE
Key class conflicts

### ISSUE THREAD

**Issue by martindufort** [berlincode/ndb-orm#2]
Looks like there is a conflict between the ndb_orm key module and the associated google.datastore.cloud key module. 

Any timeline into integrating the ndb.Key functionality ?

**Comment by berlincode** [comment]
The original key class from ndb was intentionally removed. There is only a wrapper which has an interface nearly identical to the old ndb.key class which create google.datastore.cloud key. I've added simple support for KeyProperty. Please have a look at the recent version.
