### ISSUE TITLE
Using namespace with ndb-orm

### ISSUE THREAD

**Issue by martindufort** [berlincode/ndb-orm#3]
I need to setup multi tenancy using the namespace concept of the Cloud DataStore. 
Inspecting the code, I'm not sure this is fully implemented within the current version of the library. 

Can you help me understand what is missing to support that ? Thanks

**Comment by martindufort** [comment]
It would be interesting to  add the below assertion into the test suite.

**Assertion**: _Validate that the constraint of a namespace is properly enforced_

- Write an object with specified key "abc" using namespace "ns1"
- Change namespace to "ns2"
- Try to load object with key "abc" within namespace "ns2"
   - Should return none. 

So far, from my test, looks like specifying and changing the namespace within the datastore.Client() object has no effect into validating the above assertion.

**Comment by berlincode** [comment]
I have made some small fixes and added a test to show that namespaces basically work. Though I think the current implementation could be improved...

Have a look here:
https://github.com/berlincode/ndb-orm/blob/master/tests/tests_namespace.py

I hope this helps.

**Comment by martindufort** [comment]
Super !!! 
Let me pull 0.9.0 and integrate in my code. Will report back. 

Thanks
