### ISSUE TITLE
"KeyBase is not implemented yet" in version 0.9.0

### ISSUE THREAD

**Issue by martindufort** [berlincode/ndb-orm#4]
I'm trying to directly instantiate a ndb.Key() to use with my Entity object. 

However looking at the source code, this instantiates a KeyBase class which is not yet implemented. 
I'm not sure if you have a different version of this class.

`
raise NotImplementedError('KeyBase class is not set up (yet)')
NotImplementedError: KeyBase class is not set up (yet)
`
Instantiated from `KeyClass` line 49.

**Comment by berlincode** [comment]
Yes. Basically I didnt't want to have a hard depency to google.cloud.datastore and because of problems when loading google.cloud.datastore which itself load grpc in a forking environment I decided to do runtime patching via:

>>> import ndb_orm as ndb
>>> ndb.enable_use_with_gcd(client.project)

This should add the missing class from google.cloud.datastore.

**Comment by martindufort** [comment]
Oh yea!!! My bad!!!. I missed the "enabling" in my test code. Thanks
