### ISSUE TITLE
async variants?

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [berlincode/ndb-orm#6]
Hi @berlincode ,

We are switching from GAE standard to GAE flexible. I'm looking for a good NDB replacement and we need performance.
For the C10K problem Python3 has asyncio that provides high performance by event loop and asynchronous I/O. 

Why doesn't your ndb-orm have _async variants?

How do we make ndb-orm to support fully async operations?
I found [this one](https://github.com/transceptor-technology/aiogcd). Is it possible to combine ndb-orm with it?

**Comment by berlincode** [comment]
This project is intended to be used with google-cloud-datastore. Basically it can be used as some kind of wrapper for it.

There are imho at least two different ways to connect to google's datastore:
* a grpc/protobuf based interface (which is used by google-cloud-datastore)
* and a simpler (less powerful) rpc interface (which is used by aiogcd)

The original ndb interface used nearly the same interface which is now used by google-cloud-datastore. There are several ndb feature that require this interface.

At the time I started this project I already had a look at aiogcd, but decided to go with google-cloud-datastore to create a high compatibility to ndb.

If google-cloud-datastore will one day support async methods we can make immediately use of it.

Besides this I was very successful to use python3 async methods to create a database-batcher on top of ndb-orm and used pythons async method to make requests to other databased (redis) and prepare some calculations while ndb-orm fetches the data.

I hope this helps somehow. I'm not able to supply direct async functions for ndb-orm until the google-cloud-datastore will.

**Comment by HIRANO-Satoshi** [comment]
Thanks for explanation.

I'm thinking to migrate to Go now.
