### ISSUE TITLE
`query.py` file missing

### ISSUE THREAD

**Issue by welshamy** [berlincode/ndb-orm#7]
The `ndb-orm/query.py` file is missing.  Running any query with `Model.query()` results in error:

```
File "/home/.../venv/lib/python3.6/site-packages/ndb_orm/model.py", line 3420, in _query
    from .query import Query  # Import late to avoid circular imports.
ModuleNotFoundError: No module named 'ndb_orm.query'
```
[README.md][1] says:

> This is not a drop-in replacement for the whole ndb package (no ndb.context, ndb.tasklets, ndb.query or ndb.Key), but allows you to use ndb.model classes.

So the file might be intentionally omitted.  This code throws an exception when properly used though.

How to reproduce:

 - Create an entity `Person`
 - Call `Person.query()`

[1]: https://github.com/berlincode/ndb-orm/blob/master/README.md

**Comment by berlincode** [comment]
Hi.

You are completely right. The query.py file is missing intentionally. Ndb-orm aims to make a migration as simple as possible. The focus is to make ndb models usable on platforms where ndb is not supported.

For creating queries you (currently) need to the underlying gcloud datastore directly:
```python
datastore_client.query(
    kind=Person._get_kind()
)
```

I think it should be possible to create a wraper for most common query use cases. I'm currently missing time for this.

I've added 'tests_query_simply.py' to show how to use queries (in 'tests' subdirectory).

Hope this helps.
